### ISSUE TITLE
Running RDMP CL (rdmp.exe) it should start the GUI if no parameters are set

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#1067]
**Is your feature request related to a problem? Please describe.**
When trying to start the RDMP CL GUI you're required to add the "gui" flag.

**Describe the solution you'd like**
By default rdmp.exe does not have a default operation and only displays help. To increase accessibility of the RDMP CL GUI suggest that the default operation of running the rdmp.exe without any command arguments should be to load the GUI.

**Comment by tznind** [comment]
Not sure I agree with this.  The new user experience of the CLI should be positive.  Before the `gui` option works a user needs to:

- Install RDMP (e.g. `rdmp install ...`)
- Configure Databases.yaml 

Otherwise they just see a big stack of error messages.  I think the default system behavior of showing help is more consistent with CLI behaviours.  For example if you just type `dotnet` alone it shows the help.

Theres quite a lot the rdmp cli does appart from gui like listing objects, running extractions etc.

**Comment by RoyMudie** [comment]
Usability / accessibility of command line GUI to be improved upon via changes to desktop version of RDMP to better support hand-off to the command line client to run background processes.
