### ISSUE TITLE
Hide filter parameters for published filters

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#1180]
**Is your feature request related to a problem? Please describe.**
Published filters show the parameter values in the tree which might cause confusion as these values are likely never used by the user when being added to a catalogue.

**Describe the solution you'd like**
Hide the parameters so they don't confuse the user next to Known Good Value Sets (which are helpful)

**Comment by tznind** [comment]
There are use cases where having these vanish is problematic.  For example, you add a second parameter to a filter and need to set it up and add it to the existing 'value sets'

![image](https://user-images.githubusercontent.com/31306100/169779628-59e8400d-a196-4b2f-be3b-e1fc798efb06.png)

You want to change the datatype on a parameter:
![image](https://user-images.githubusercontent.com/31306100/169779799-0422b460-b4ea-4e9a-b855-22d61abf4b9e.png)

Also the user should be able to add a filter and opt not to use any of the value sets (in which case the default / top level) parameter values should be added.

I think the correct solution to this usability issue is simply to update ProblemProvider to not report 'no value defined' as a problem so that it doesn't show in red.
