### ISSUE TITLE
ProblemProvider should flag when JoinInfo columns have different collations

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1288]
**Is your feature request related to a problem? Please describe.**
In MySql (and probably sql server too) collation differences can cause massive performance degredation.

**Describe the solution you'd like**
Flag in red (ProblemProvider) when collations do not match on join keys

**Comment by jas88** [comment]
I think the issue was copying between different MySQL versions - the SMI side had a newer version than eDRIS, so had been set up to use something like `utf8mb4_0900_ai_ci` while eDRIS's could only support `utf8mb4_unicode_520_ci` meaning it couldn't be copied at the time. An ALTER would take a while on a big table, but hopefully only need to run once for each affected table then it's fixed for all future operations.
