### ISSUE TITLE
Identify tables/databases and privileges needed for a data load

### ISSUE THREAD

**Issue by jas88** [HicServices/RDMP#1289]
**Is your feature request related to a problem? Please describe.**

Apparently the current RDMP load isn't detailed/clear enough about identifying the databases/tables it will touch (see JIRA row).

**Describe the solution you'd like**

GUI and/or CLI listing, e.g.:

```
$ rdmp describe load 123
images=Hostname=bigdb.example.com;Username=rdmp
metadata=Hostname=bigdb.example.com;Username=rdmp
platform=Hostname=rdmpsql.example.com;Username=fbloggs
ALTER,INSERT,UPDATE ON images.CT, images.MR, images.OT
SELECT ON metadata.patientid
INSERT,UPDATE ON platform.logging, platform.dqe
```

**Describe alternatives you've considered**

Figuring it out manually; trial and error (run load until it fails with "access denied to UPDATE blah", grant access to blah, try again...)

**Additional context**

Syntax above is a rough suggestion, but the core idea should be useful, hopefully not too hard to add to RDMP/RdmpDicom?

**Comment by tznind** [comment]
I think we should start with some FAQs about privelleges required for the RDMP user account in general (to log, run DQE etc)

There is the load diagram which shows which servers/databases will get hit up by the load:

![image](https://user-images.githubusercontent.com/31306100/178520192-1f283728-3c28-40e9-af24-05f8cc96eeef.png)

There is no console gui version of this or command line but it would be a logical place to build from and would have the added benefit pulling code out of UI layer into core which is good for maintenence.

I'm not sure about file system permissions and that kind of thing.  I think that might best be handled with documentation rather than code and definetly not high level code in the RDMP.Core package as modules can do just about anything so they should undertake to document this kind of thing themselves.

**Comment by tznind** [comment]
Incidentally there is this bit of the integration testing in RDMP that allows for running tests as limited access users:

https://github.com/HicServices/RDMP/blob/f19510b1f01336702fb782e4605cd2a126db0de8/Tests.Common/TestDatabases.txt#L14-L23

But its not fully developed and has suffered a bit from bitrot and not actually being incorporated into ci
