### ISSUE TITLE
Deprecation of IgnoreQuotes in CsvHelper v 20.0.0

### ISSUE THREAD

**Issue by jas88** [HicServices/RDMP#226]
**Describe the bug**
The IgnoreQuotes parameter has been removed from CsvHelper as of v20.0.0 - need to find either a workaround to preserve this functionality, or document and reflect this removal.

**Additional context**
Unknown: how important is this option in actual RDMP usage? Would removing it upset people enough that it needs to be re-implemented somehow?

**Comment by tznind** [comment]
I think we should permenantly stop updating this library because reading and writing csv files is very core to RDMP and we already have a lot of corrupt file workarounds and stuff (see https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/CSVHandling.md).  I don't think its worth the risk of breaking stuff that we don't learn about for weeks.

**Comment by jas88** [comment]
OK - I've marked it as ignored in dependabot config and closed the PR. Might still cause issues with SMI consuming RDMP as a plugin and getting mismatched versions?

**Comment by tznind** [comment]
I would suggest that we freeze it for SMI too.

**Comment by rkm** [comment]
I think freezing a dependency for your own application is fine, however doing the same for libs that are consumed by other projects  is problematic. If we pin a library dependency, then this will cause unresolvable builds as soon as another dependency specifies a min version greater than the pin here.

I'm not completely familiar with the RDMP project layout, but would it be possible to leave CsvHelper un-pinned for the nupgk that you publish? Alternatively, there seems to be some upgrade paths suggested [here](https://github.com/JoshClose/CsvHelper/issues/1659) and [here](https://stackoverflow.com/questions/65793127/upgrading-from-csvhelper-fix-breaking-changes) that we could look into? I'd be happy to investigate a fix if that unblocks things here.

**Comment by jas88** [comment]
Freezing certainly isn't ideal - the trouble is the API changed between versions, so RDMP can either be compatible with v19's API or with v20+, not both. The first link sounds like v21 has restored the functionality, we just need to replace the IgnoreQuotes=true with Mode=NoEscape or something similar, and test this does what we need?

**Comment by tznind** [comment]
For info the `IgnoreQuotes` flag dealt with the following situation:

```
Field1,Field2
1, Watch out guys its Billie "The Killer" Cole
2, "The Killer"? I've heard of him hes a bad un
```

I have written a test to reproduce the issue:
https://github.com/HicServices/RDMP/commit/9dce75fefcff912c1042f6c8da7ff81f9ee8decb

Sometimes a data provider will do something like strip commas and newlines from data being extracted.  If we could load that before but suddenly can't now then that's a problem.

The reason the flag is exposed in RDMP is because the data has been encountered (I wouldn't just have added it for kicks ;) )

**Comment by tznind** [comment]
@rkm saw your draft PR.  Looks interesting....

I wonder if it is possible to excise the dependency on CsvHelper from BadMedicine.  Might take a look at that on Monday.  BadMedicine CLI will need it to spit out files but might be able to remove the dependency from the library part of it.

**Comment by rodyfernandez** [comment]
Mode = CsvMode.NoEscape,

**Comment by tznind** [comment]
Fixed we are now using the latest version CsvHelper with NoEscape being used for the IgnoreQuotes feature of the attacher
