### ISSUE TITLE
New Catalogue From Existing Table creates duplicate TableInfos

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#265]
**Describe the bug**

Using File=>New results in double import of TableInfo

![image](https://user-images.githubusercontent.com/31306100/109529472-af112780-7aad-11eb-93cb-aa307ec2bd4d.png)

**Expected behavior**
1 Table Info and 1 Catalogue

Not 2 TableInfos and 1 Catalogue

**RDMP Version**
v4.2.4

**Comment by howff** [comment]
A couple of slight differences:
* Instead of using File|New I right-clicked on the \ingest\extraction\ path and did it from there (not sure how I'd associated it with that path otherwise)
* I've just remembered that I tried to catalogue it twice but didn't know the answer to the question Is Extractable Column Type (i.e. "Core") so I clicked on Cancel, got the answer elsewhere, and did the process again. Maybe the cancel didn't cancel everything?

**Comment by tznind** [comment]
Can confirm this behaviour, when cancelling an import of an existing Table leaves the `TableInfo` in the database but no `Catalogue`.

![image](https://user-images.githubusercontent.com/31306100/109664668-47b6ae80-7b65-11eb-8aba-ca2c17dc96f8.png)

It should be possible to do something about this.  Its slightly complicated in that it is a 2 stage process:

1. Create TableInfo pointing at database
2. Create Catalogue wired up to TableInfo

You can do stage 1 without doing stage 2 and you can ddo stage 2 on it's own too (right click an existing `TableInfo` and add a new Catalogue that extracts from it).

I will take a look at how to track the users workflow into the UI so it deletes the appropriate artifacts.
