### ISSUE TITLE
Show Project Number in 'Execute Extraction' and 'Edit Extraction' tab names [Magalie]

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#621]
![image](https://user-images.githubusercontent.com/31306100/139669729-d741b1bb-c7c9-4ee1-856b-0e29c4d36e4a.png)

> May I suggest the Configuration Extraction show the project number and CI name? if the CIs have similar generic names (Initial extraction, Release1 etc....) it could be difficult to know which one is open, specially if it comes from the latest tabs opened by the user in RDMP once the app is started. Maybe including the project num would help identify a CI

**Comment by RoyMudie** [comment]
Tried a couple of ideas how best to display this:
![image](https://user-images.githubusercontent.com/5470814/143464407-04b0ce3f-d104-4f7b-bd9f-ba745ff62ab8.png)

Ultimately because project numbers have a shorter length than both Project names and Extraction configurations it was suggested that the project number be placed at the start of the tab title
![image](https://user-images.githubusercontent.com/5470814/143464556-04c6da47-0d46-4639-aa86-bcee80427689.png)

Because this could be confusing for the user, I've added a tabToolTip property that can be set seperately from the title so we can set that seperately. e.g.
![image](https://user-images.githubusercontent.com/5470814/143464712-7bd5a6f3-3a0c-442d-b7b0-a7a29a393b4c.png)

**Comment by RoyMudie** [comment]
Regression in the formatting introduced by 89d6a57 - needs updated so project number is at start of Tab name for easy visaiblty when multiple tabs with same extraction name from different projects is open visibility
