### ISSUE TITLE
Slow performance when editing SelectedDataSets 

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#838]
**Describe the bug**
When modifiying the selected dataset columns the application is doing checks and savings on each operation resulting in it being quite slow/unresponsive.

![image](https://user-images.githubusercontent.com/5470814/146363017-d62bcbc0-17de-4a0a-ba78-5a64f377e16a.png)

Can we speed this up? Would it be possible to stop auto saving?

**Comment by tznind** [comment]
The performance bottleneck is in the `publish` system not the save system.  There is no 'staged operations' state in RDMP.  If you see multiple objects in a UI tab then any changes are applied as they occur.

This is a good thing because it allows other tabs to respond to the changes.  For example:
![image](https://user-images.githubusercontent.com/31306100/146364675-bd51ad18-8cd8-49fe-9374-d659cc547ac6.png)

**Comment by RoyMudie** [comment]
I think we're talking about the same thing here. When you say "speed up publishing" I'm thinking along the lines of the UI/UX change to address as well, as DLS described the problem as:
`"most of the time I need to refresh the content of a catalogue because extractability has changed. So just click on << then Select Core then > (3 clicks)"`

Surely we could improve this process so that they're not removing and adding everything. Maybe there needs to be something more like a "sync with core" so that it's one button click and the number of operations is reduced.
