### ISSUE TITLE
CIC using chaced data when enabling/disabling AggregateFilters in Patient Index Table [Sindy]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#849]
**Describe the bug**
When a CIC is created with multiple AggregateFilters for the Paitent Index Table, if those filters are enabled/disabled RDMP appears to use the last cached query rather than a fresh query for any depedant AggregateConfiguration.

![image](https://user-images.githubusercontent.com/5470814/148216386-5a5ec39a-3128-4d16-8fb2-c0d7a2f3310d.png)

**To Reproduce**
1. Create a CIC with multiple filters
2. Disable one filter within the Patient Index Table
3. Use green execute button to run the CIC and note the number of results
3. Enable the filter and disable another one in the Patient Index Table
4. Use green execute button to run the CIC and note the number of results for the AggretateConfiguration haven't changed.

Can be resolved by clearning the cache.

**Additional context**

**Comment by tznind** [comment]
Ok I understand how this happens.  To determine whether a cache hit is success or not we look at the SQL executed.  If it matches then we accept the cache hit.  The case where this happens is:

1. Run joinable
2. Cache joinable
3. Run aggregate 

At this point it caches the result of the aggregate as:
```
Select chi from Bob
JOIN
select * from CachedIndexTable
```

4. change joinable
5. cache change joinable
6. Run aggregate

Here the engine looks and sees that the joinable is fully cached and the built SQL is the same for the aggregate so it pulls the cached result that was generated at step 3.

I think the fix is that whenever a joinable (patient index table) is detected as stale in the cache lookup stage that we clear the cache results of anyone using it.
