### ISSUE TITLE
Wrong platform database listed on startup, plus increased startup time

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#91]
Hi, I have a set of platform databases setup on a local vm [scr1] which works fine. On startup though, the client displays that it is connecting to localhost [scr2], and then waits for some timeout before properly connecting to the remote platform database [scr3]. Closing the dialogue in [scr2] also results in the remote platform databases being loaded.

RDMP v4.1.6.

[scr1]: https://i.fluffy.cc/NNnPXcMz9th2Hj8dlrFk19kHlNz1fDVM.PNG
[scr2]: https://i.fluffy.cc/sF74rzBWdSqM8Ln01j1CNRffsv7mHv3S.PNG
[scr3]: https://i.fluffy.cc/tvfjwX5VWGw8tZbKBqBK6rBn4kJDRnXR.PNG

**Comment by tznind** [comment]
Looks like it waiting to connect to `TEST_DQE` which is the default data quality engine.  It is not a mandatory database for launching the main UI.  To diagnose if this is the problem please try:

![image](https://user-images.githubusercontent.com/31306100/90019035-c4f00400-dca5-11ea-99af-2be8d103b206.png)

If the settings for your TEST_DQE are dodgy then you can either correct them or delete the entry entirely (which will prevent DQE related stuff being enabled).

**Comment by rkm** [comment]
That worked, thanks. I'll close this.

Would it make sense (and be possible) to default these connection strings to the same as the platform databases?

**Comment by tznind** [comment]
> Would it make sense (and be possible) to default these connection strings to the same as the platform databases?

Glad you were able to fix it.  

When you install RDMP (from command line or running GUI client for the first time) it will create all the databases on the listed server (e.g. `localhost`).  This includes DQE, Logging etc.  The locations of the DQE and Logging databases are written into the `ExternalDatabaseServer` table along with encrypted credentials (or to use integrated security).

If you change your connection string in the gui client (e.g. to your machine name) then there will be a new route to the main platform databases but the values stored in the `ExternalDatabaseServer` table will not be affected.

`ExternalDatabaseServer` stores server name, database name, username etc in seperate fields rather than a connection string so theoretically we could have a null server name mean 'use the same server name as the Catalogue' but that would probably be undesireable.
